BUTPFIS/BUTPFIS.web/Controllers/AdminCoursesController.cs
using BUTPFIS.web.Data;
using BUTPFIS.web.Models.Domain;
using BUTPFIS.web.Models.ViewModels;
using BUTPFIS.web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace BUTPFIS.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminCourseController : Controller
    {
        private readonly ICourseRepository courseRepository;

        public AdminCourseController(ICourseRepository courseRepository)
        {
            this.courseRepository = courseRepository;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddCourseRequest addCourseRequest)
        {
            if (ModelState.IsValid == false)
            {
                return View();
            }


            var courseInfo = new CourseInfo
            {
                CourseName = addCourseRequest.CourseName
            };

            await courseRepository.AddAsync(courseInfo);

            return RedirectToAction("List");
        }

        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List(string? searchQuery)
        {
            ViewBag.SearchQuery = searchQuery;  

            var courseinfos = await courseRepository.GetAllASync(searchQuery);

            return View(courseinfos);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var courseinfo = await courseRepository.GetAsync(id);

            if (courseinfo != null)
            {
                var editCourse = new EditCourse
                {
                    CourseId = courseinfo.CourseId,
                    CourseName = courseinfo.CourseName
                };

                return View(editCourse);
            }

            return View(null);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditCourse editCourse)
        {
            // map view model back to domain model
            var editCourseInfo = new CourseInfo
            {
                CourseId = editCourse.CourseId,
                CourseName = editCourse.CourseName
            };

            var updatedCourse = await courseRepository.UpdateAsync(editCourseInfo);

            if (updatedCourse != null)
            {
                // Show success notification
            }
            else
            {
                // Show error notification
            }

            return RedirectToAction("List", new { id = editCourse.CourseId });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditCourse editCourse)
        {
            var deletedCourse = await courseRepository.DeleteAsync(editCourse.CourseId);

            if (deletedCourse != null)
            {
                //Show success notification
                return RedirectToAction("List");
            }

            // Show error notification
            return RedirectToAction("Edit", new { id = editCourse.CourseId });
        }
    }
}

BUTPFIS/BUTPFIS.web/Controllers/AdminFacultyController.cs
using Azure;
using BUTPFIS.web.Data;
using BUTPFIS.web.Models.Domain;
using BUTPFIS.web.Models.ViewModels;
using BUTPFIS.web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace BUTPFIS.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminFacultyController : Controller
    {
        private readonly ICourseRepository courseRepository;
        private readonly IFacultyRepository facultyRepository;

        public AdminFacultyController(ICourseRepository courseRepository, IFacultyRepository facultyRepository)
        {
            this.courseRepository = courseRepository;
            this.facultyRepository = facultyRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            // get courses from repository
            var courses = await courseRepository.GetAllASync();

            var model = new AddFacultyRequest
            {
                Courses = courses.Select(x => new SelectListItem { Text = x.CourseName, Value = x.CourseId.ToString()})
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddFacultyRequest addFacultyRequest)
        {
            var facultyInfo = new FacultyInfo
            {
                Name = addFacultyRequest.Name,
                Designation = addFacultyRequest.Designation,
                MobileNo = addFacultyRequest.MobileNo,
                Email = addFacultyRequest.Email,
                FacultyImageUrl = addFacultyRequest.FacultyImageUrl,
                PersonalInfo = addFacultyRequest.PersonalInfo,
                GoogleScholarLink = addFacultyRequest.GoogleScholarLink,
                ResearchGateLink = addFacultyRequest.ResearchGateLink,
                Expertise = addFacultyRequest.Expertise,
                Experience = addFacultyRequest.Experience,
                Education = addFacultyRequest.Education,
                Honours = addFacultyRequest.Honours,
                Patents = addFacultyRequest.Patents,
                Publications = addFacultyRequest.Publications,
                Seminar = addFacultyRequest.Seminar
            };

            // Map Courses from Selected Courses
            var selectedCourses = new List<CourseInfo>();
            foreach (var selectedCourseId in addFacultyRequest.SelectedCourses)
            {
                var selectedCourseIdAsGuid = Guid.Parse(selectedCourseId);
                var existingCourse = await courseRepository.GetAsync(selectedCourseIdAsGuid);

                if (existingCourse != null)
                {
                    selectedCourses.Add(existingCourse);
                }
            }

            // Mapping courses back to domain model
            facultyInfo.CourseInfos = selectedCourses;

            await facultyRepository.AddAsync(facultyInfo);

            return RedirectToAction("List");
        }

        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List(string? searchQuery)
        {
            ViewBag.SearchQuery = searchQuery;

            var facultyinfos = await facultyRepository.GetAllASync(searchQuery);

            return View(facultyinfos);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var facultyinfo = await facultyRepository.GetAsync(id);
            var coursesDomainModel = await courseRepository.GetAllASync();

            if (facultyinfo != null)
            {
                var model = new EditFaculty
                {
                    FId = facultyinfo.FId,
                    Name = facultyinfo.Name,
                    Designation = facultyinfo.Designation,
                    MobileNo = facultyinfo.MobileNo,
                    Email = facultyinfo.Email,
                    FacultyImageUrl = facultyinfo.FacultyImageUrl,
                    PersonalInfo = facultyinfo.PersonalInfo,
                    GoogleScholarLink = facultyinfo.GoogleScholarLink,
                    ResearchGateLink = facultyinfo.ResearchGateLink,
                    Expertise = facultyinfo.Expertise,
                    Experience = facultyinfo.Experience,
                    Education = facultyinfo.Education,
                    Honours = facultyinfo.Honours,
                    Patents = facultyinfo.Patents,
                    Publications = facultyinfo.Publications,
                    Seminar = facultyinfo.Seminar,
                    Courses = coursesDomainModel.Select(x => new SelectListItem
                    {
                        Text = x.CourseName,
                        Value = x.CourseId.ToString()
                    }),
                    SelectedCourses = facultyinfo.CourseInfos.Select(x => x.CourseId.ToString()).ToArray()
                };

                return View(model);
            }

            return View(null);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditFaculty editFaculty)
        {
            // map view model back to domain model
            var facultyDomainModel = new FacultyInfo
            {
                FId = editFaculty.FId,
                Name = editFaculty.Name,
                Designation = editFaculty.Designation,
                MobileNo = editFaculty.MobileNo,
                Email = editFaculty.Email,
                FacultyImageUrl= editFaculty.FacultyImageUrl,
                PersonalInfo = editFaculty.PersonalInfo,
                GoogleScholarLink = editFaculty.GoogleScholarLink,
                ResearchGateLink = editFaculty.ResearchGateLink,
                Expertise = editFaculty.Expertise,
                Experience = editFaculty.Experience,
                Education = editFaculty.Education,
                Honours = editFaculty.Honours,
                Patents = editFaculty.Patents,
                Publications = editFaculty.Publications,
                Seminar= editFaculty.Seminar
            };

            // Map courses to domain model

            var selectedCourses = new List<CourseInfo>();
            foreach (var selectedCourse in editFaculty.SelectedCourses)
            {
                if (Guid.TryParse(selectedCourse, out var course))
                {
                    var foundCourse = await courseRepository.GetAsync(course);

                    if (foundCourse != null)
                    {
                        selectedCourses.Add(foundCourse);
                    }
                }
            }

            facultyDomainModel.CourseInfos = selectedCourses;

            var updatedFaculty  = await facultyRepository.UpdateAsync(facultyDomainModel);

            if (updatedFaculty != null)
            {
                // Show success notification
            }
            else
            {
                // Show error notification
            }

            return RedirectToAction("List", new { id = editFaculty.FId});
        }

        
        [HttpPost]
        public async Task<IActionResult> Delete(EditFaculty editFaculty)
        {
            var deletedFaculty = await facultyRepository.DeleteAsync(editFaculty.FId);

            if (deletedFaculty != null)
            {
                //Show success notification
                return RedirectToAction("List");
            }

            // Show error notification
            return RedirectToAction("Edit", new { id = editFaculty.FId });
        }

        public async Task<IActionResult> GetFacultiesByCourse(string courseName)
        {
            var faculties = await facultyRepository.GetFacultiesByCourseAsync(courseName);
            return View(faculties);
        }

    }
}

BUTPFIS/BUTPFIS.web/Controllers/EditProfileController.cs
using BUTPFIS.web.Models.Domain;
using BUTPFIS.web.Models.ViewModels;
using BUTPFIS.web.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace BUTPFIS.web.Controllers
{
    public class EditProfileController : Controller
    {
        private readonly IUserRepository userRepository;
        private readonly ICourseRepository courseRepository;
        private readonly IFacultyRepository facultyRepository;
        private readonly UserManager<IdentityUser> userManager;

        public EditProfileController(IUserRepository userRepository, ICourseRepository courseRepository, IFacultyRepository facultyRepository, UserManager<IdentityUser> userManager)
        {
            this.userRepository = userRepository;
            this.courseRepository = courseRepository;
            this.facultyRepository = facultyRepository;
            this.userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Edit()
        {
            var user = await userManager.GetUserAsync(User);
            if (user == null) return NotFound("User not found.");

            var facultyinfo = await userRepository.GetAsync(user.Email);
            var coursesDomainModel = await courseRepository.GetAllASync(null);

            if (facultyinfo != null)
            {
                var model = new EditFaculty
                {
                    FId = facultyinfo.FId,
                    Name = facultyinfo.Name,
                    Designation = facultyinfo.Designation,
                    MobileNo = facultyinfo.MobileNo,
                    Email = facultyinfo.Email,
                    FacultyImageUrl = facultyinfo.FacultyImageUrl,
                    PersonalInfo = facultyinfo.PersonalInfo,
                    GoogleScholarLink = facultyinfo.GoogleScholarLink,
                    ResearchGateLink = facultyinfo.ResearchGateLink,
                    Expertise = facultyinfo.Expertise,
                    Experience = facultyinfo.Experience,
                    Education = facultyinfo.Education,
                    Honours = facultyinfo.Honours,
                    Patents = facultyinfo.Patents,
                    Publications = facultyinfo.Publications,
                    Seminar = facultyinfo.Seminar,
                    Courses = coursesDomainModel?.Select(x => new SelectListItem
                    {
                        Text = x.CourseName,
                        Value = x.CourseId.ToString(),
                        Selected = facultyinfo.CourseInfos.Any(c => c.CourseId == x.CourseId)
                    }) ?? Enumerable.Empty<SelectListItem>(),
                    SelectedCourses = facultyinfo.CourseInfos?.Select(x => x.CourseId.ToString()).ToArray() ?? Array.Empty<string>()
                };

                return View(model);
            }

            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditFaculty editFaculty)
        {            
            // Map view model back to domain model
            var facultyDomainModel = new FacultyInfo
            {
                FId = editFaculty.FId,
                Name = editFaculty.Name,
                Designation = editFaculty.Designation,
                MobileNo = editFaculty.MobileNo,
                Email = editFaculty.Email,
                FacultyImageUrl = editFaculty.FacultyImageUrl,
                PersonalInfo = editFaculty.PersonalInfo,
                GoogleScholarLink = editFaculty.GoogleScholarLink,
                ResearchGateLink = editFaculty.ResearchGateLink,
                Expertise = editFaculty.Expertise,
                Experience = editFaculty.Experience,
                Education = editFaculty.Education,
                Honours = editFaculty.Honours,
                Patents = editFaculty.Patents,
                Publications = editFaculty.Publications,
                Seminar = editFaculty.Seminar
            };

            var selectedCourses = new List<CourseInfo>();
            foreach (var selectedCourse in editFaculty.SelectedCourses)
            {
                if (Guid.TryParse(selectedCourse, out var course))
                {
                    var foundCourse = await courseRepository.GetAsync(course);

                    if (foundCourse != null)
                    {
                        selectedCourses.Add(foundCourse);
                    }
                }
            }

            facultyDomainModel.CourseInfos = selectedCourses;

            var updatedFaculty = await facultyRepository.UpdateAsync(facultyDomainModel);

            if (updatedFaculty != null)
            {
                // Show success notification
                return RedirectToAction("Edit");
            }
            else
            {
                // Show error notification
                return RedirectToAction("Edit");
            }

            
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditFaculty editFaculty)
        {
            var deletedFaculty = await facultyRepository.DeleteAsync(editFaculty.FId);

            if (deletedFaculty != null)
            {
                //Show success notification
                TempData["Notification"] = "Faculty entry successfully deleted.";
                return RedirectToAction("Index", "Home");
            }

            // Show error notification
            return RedirectToAction("Edit", new { id = editFaculty.FId });
        }

    }
}

BUTPFIS/BUTPFIS.web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

@{
    var isAdmin = User.IsInRole("Admin");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BUTP - Faculty Information System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BUTPFIS.web.styles.css" asp-append-version="true" />

    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>

    <style>
        .header {
            background-color: #343a40; /* Same color as navbar */
            color: #fff;
            text-align: center;
            padding: 10px 0; /* Adjusted padding */
            position: relative;
        }

            .header img {
                width: 100px;
                height: 100px;
                margin: 0 10px; /* Reduced margin */
            }

            .header .uni-name-tamil,
            .header .uni-name-english {
                font-size: 24px;
                font-weight: bold;
                display: inline-block;
                margin: 0 5px; /* Adjusted margin */
            }

            .header .uni-name-english {
                font-size: 30px;
            }

            .header .address {
                font-size: 14px;
                margin-top: 5px;
            }

        .navbar-nav {
            flex-grow: 1;
        }

            .navbar-nav .nav-item {
                margin-right: 15px;
            }

        .btn-custom {
            background-color: #01010fed;
            color: #FFFFFF;
            border: none;
        }

            .btn-custom:hover {
                background-color: #020202;
                color: #FFFFFF;
            }

        .content {
            flex: 1;
            background-color: white;
            color: black;
            padding: 20px;
        }

        .footer {
            padding: 10px 0;
            font-size: 0.875rem;
            background-color: #f8f9fa;
            text-align: center;
        }
    </style>
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-5 text-end">
                    <div class="uni-name-tamil">பாரதிதாசன் பல்கலைக்கழகம்</div>
                </div>
                <div class="col-md-2 text-center">
                    <img src="https://res.cloudinary.com/djg5iadcq/image/upload/v1722408040/pzbehl2yias2jgyq0tha.png" alt="College Symbol" style="width: 110px; height: 100px; margin: 0 10px; transform: rotate(5deg);">
                </div>
                <div class="col-md-5 text-start">
                    <div class="uni-name-english">Bharathidasan University</div>
                </div>
            </div>
        </div>
    </header>

    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Faculty Information System</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>

                    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="AdminCourse"
                                       asp-action="Add">
                                        Add Course
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="AdminFaculty"
                                       asp-action="Add">
                                        Add Faculty (Admin)
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="AdminCourse"
                                       asp-action="List">
                                        All Courses
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="AdminFaculty"
                                       asp-action="List">
                                        All Faculty Information
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="AdminUsers"
                                       asp-action="List">
                                        Manage Faculties
                                    </a>
                                </li>
                            </ul>
                        </li>
                    }
                </ul>

                <div class="d-flex align-items-center">
                    @if (signInManager.IsSignedIn(User))
                    {
                        <div class="nav-item dropdown me-3">
                            @if (!isAdmin)
                            {
                                <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    @User?.Identity?.Name
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item"
                                           asp-area=""
                                           asp-controller="EditProfile"
                                           asp-action="Edit">
                                            Edit My Profile
                                        </a>
                                    </li>
                                </ul>
                            }
                            else
                            {
                                <span class="nav-link text-light">@User?.Identity?.Name</span>
                            }
                        </div>
                        <a class="btn me-3 bg-light text-dark"
                           asp-area=""
                           asp-controller="Account"
                           asp-action="Logout">Logout</a>
                    }
                    else
                    {
                        <a class="btn me-3 bg-light text-dark"
                           asp-area=""
                           asp-controller="Account"
                           asp-action="Login">Login</a>
                        <a class="btn me-3 bg-light text-dark"
                           asp-area=""
                           asp-controller="Account"
                           asp-action="Register">Register</a>
                    }
                </div>
            </div>
        </div>
    </nav>

    <div class="content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="container">
            &copy; 2024 - BUTPFIS.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>